<a href="https://colab.research.google.com/github/bushujee/100-days-of-machine-learning/blob/main/integer_encoding_simplernn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np

docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [41]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')

In [42]:
tokenizer.fit_on_texts(docs)

In [43]:
tokenizer.word_index

{'<nothing>': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'bharat': 13,
 'mata': 14,
 'modi': 15,
 'ji': 16,
 'inquilab': 17,
 'zindabad': 18}

In [ ]:
tokenizer.word_counts

In [ ]:
tokenizer.document_count

In [44]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

In [45]:
from keras.utils import pad_sequences

In [46]:
sequences = pad_sequences(sequences,padding='post')

In [40]:
sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)

In [59]:
import numpy as np
sequences = np.array(sequences)
print("Max index:", sequences.max())
print("Min index:", sequences.min())


Max index: 18
Min index: 0


In [67]:
from tensorflow.keras.layers import Dense, Flatten
model = Sequential()

model = Sequential([
    Embedding(input_dim=19, output_dim=2, input_shape=(5,)),
    # Flatten()
])

model.summary()


Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ (None, 5, 2)           │            38 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 38 (152.00 B)

 Trainable params: 38 (152.00 B)

 Non-trainable params: 0 (0.00 B)

In [68]:
model.compile('adam','accuracy')


In [69]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
[[[-0.045906   -0.0318114 ]
  [-0.01432054  0.00615619]
  [-0.00938494  0.00327318]
  [-0.00938494  0.00327318]
  [-0.00938494  0.00327318]]

 [[-0.01432054  0.00615619]
  [-0.01432054  0.00615619]
  [-0.00938494  0.00327318]
  [-0.00938494  0.00327318]
  [-0.00938494  0.00327318]]

 [[-0.03209385  0.00696086]
  [-0.03209385  0.00696086]
  [ 0.00898613 -0.0093041 ]
  [-0.00938494  0.00327318]
  [-0.00938494  0.00327318]]

 [[-0.01817077  0.02282545]
  [ 0.00413648 -0.04690372]
  [-0.01817077  0.02282545]
  [-0.01432054  0.00615619]
  [-0.01817077  0.02282545]]

 [[ 0.00429329  0.04590729]
  [-0.04036365  0.00931891]
  [-0.00397886  0.04338681]
  [-0.04391707 -0.02738936]
  [-0.00938494  0.00327318]]

 [[-0.02467446 -0.00475669]
  [-0.02467446 -0.00475669]
  [-0.00938494  0.00327318]
  [-0.00938494  0.00327318]
  [-0.00938494  0.00327318]]

 [[ 0.03428734 -0.02891888]
  [ 0.03428734 -0.02891888]
  [-0.00938494  0.00327318]
  [-0.00938494  0.00327318

In [79]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [75]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [76]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [97]:
X_train.max()

np.int32(88585)

In [92]:
import numpy as np
sequences = np.array(X_train)
print("Max index:", sequences.max())
print("Min index:", sequences.min())


Max index: 88585
Min index: 0


In [95]:
# nodel=sequential()
model=Sequential([
    Embedding(input_dim=88586,output_dim=2,input_shape=(50,)),
    SimpleRNN(32,return_sequences=False),
    Dense(1,activation='sigmoid') ,
])
model.summary()

Model: "sequential_21"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_17 (Embedding)        │ (None, 50, 2)          │       177,172 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_9 (SimpleRNN)        │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 178,325 (696.58 KB)

 Trainable params: 178,325 (696.58 KB)

 Non-trainable params: 0 (0.00 B)

In [96]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 16s 18ms/step - acc: 0.5133 - loss: 0.6924 - val_acc: 0.5942 - val_loss: 0.6655
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 14s 18ms/step - acc: 0.7359 - loss: 0.5289 - val_acc: 0.7993 - val_loss: 0.4388
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 14s 18ms/step - acc: 0.8748 - loss: 0.2969 - val_acc: 0.8010 - val_loss: 0.4485
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 19ms/step - acc: 0.9296 - loss: 0.1896 - val_acc: 0.7914 - val_loss: 0.4968
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 14s 18ms/step - acc: 0.9553 - loss: 0.1316 - val_acc: 0.7913 - val_loss: 0.6215
